DSM5Pathologies = {
    "Anxiété et troubles liés au stress": "L’anxiété est un sentiment de nervosité, d’inquiétude ou de malaise qui fait partie de l’expérience humaine normale. Elle est également présente dans de nombreuses affections mentales, y compris le trouble anxieux généralisé, le trouble panique et les phobies. Bien que chacun de ces troubles soit différent, ils se caractérisent tous par une souffrance et un dysfonctionnement spécifiquement liés à l’anxiété et la peur.",
    "Troubles Dissociatifs": "De nombreuses personnes rencontrent occasionnellement des problèmes mineurs liés à un vide dans leurs souvenirs, leurs perceptions, leur identité et leur conscience. Une personne peut, par exemple, aller quelque part en voiture, puis réaliser qu’elle ne se souvient plus du trajet. Cela peut être dû au fait qu’elle était absorbée (par des soucis personnels, une émission de radio ou une conversation avec un passager) ou simplement qu’elle rêvassait. Ce type de problème, que l’on appelle dissociation normale, ne perturbe généralement pas les activités quotidiennes.",
    "Troubles des conduites alimentaires": "Les troubles des conduites alimentaires impliquent une perturbation de l’alimentation ou du comportement lié à l’alimentation, et comprennent généralement :",
    "Troubles de l'humeur": "Les troubles de l’humeur sont des affections mentales qui se traduisent par de longues périodes de tristesse excessive (dépression), d’exaltation excessive (manie), ou les deux. Dépression et manie constituent les deux extrêmes des troubles de l’humeur.",
    "Troubles obsessionels compulsifs et apparentés": "Le trouble obsessionnel compulsif se caractérise par des obsessions, des compulsions, ou les deux. Les obsessions sont des idées, des images ou des impulsions récurrentes, persistantes, non désirées et anxiogènes. Les compulsions (aussi appelées rituels) sont des actions particulières ou des actes mentaux que des personnes se sentent obligées d’effectuer de manière répétée, pour tenter d’atténuer ou de prévenir l’anxiété causée par les obsessions.",
    "Paraphilies et troubles paraphiliques": "Les paraphilies sont des fantasmes ou des comportements sexuels fréquents et intenses portant sur des objets inanimés, des enfants ou des adultes non consentants ou bien impliquant la souffrance ou l’humiliation de soi-même ou de son partenaire. Les troubles paraphiliques sont des paraphilies entraînant une souffrance ou perturbant le fonctionnement du paraphile, ou nuisant ou susceptibles de nuire à une autre personne.",
    "Troubles de la personnalité": "Les troubles de la personnalité sont des affections mentales caractérisées par des schémas omniprésents et persistants de pensées, de perception, de réaction et de relations qui entraînent une souffrance importante pour la personne et/ou nuisent considérablement à sa capacité à fonctionner.",
    "Schizophrénie et troubles apparentés": "La schizophrénie et les troubles psychotiques apparentés ( trouble psychotique bref, trouble délirant, trouble schizo-affectif, trouble schizophréniforme, et trouble de la personnalité schizotypique) sont caractérisés par des symptômes psychotiques et, souvent, par des symptômes négatifs et un dysfonctionnement cognitif.",
    "Incongruité de genre et dysphorie de genre": "Le sexe fait référence aux caractéristiques biologiques (telles que les organes génitaux, les chromosomes et les hormones) utilisées pour classer une personne comme étant de sexe masculin ou féminin. L’identité de genre est la façon dont la personne se voit, qu’elle soit masculine, féminine ou toute autre identité de genre, qui peut correspondre ou non au sexe à la naissance.",
    "Troubles somatoformes et apparentés": "Les troubles somatoformes et apparentés sont des troubles mentaux caractérisés par une attention intense portée aux symptômes physiques (somatiques), entraînant une souffrance significative et/ou une perturbation du fonctionnement quotidien.",
    "Troubles liés à l'usage de substances": "Les médicaments et autres substances font partie intégrante de la vie de tous les jours de beaucoup de personnes, qu’elles soient utilisées à des fins médicales légales, comme une habitude (la caféine par exemple) ou à des fins récréatives (voir le tableau ).",
    "Comportement suicidaire et automutilation": "Le suicide est la mort causée par un acte d’autodestruction destiné à provoquer la mort. Les comportements suicidaires font référence aux suicides effectifs, aux tentatives de suicide et aux idées suicidaires (pensées et idées).",
}
