# Generated by Django 5.0.6 on 2024-06-14 22:33

import SafeTagAPI.models.practitioner_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SafeTagAPI", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practitioners",
            name="accessibility",
        ),
        migrations.RemoveField(
            model_name="practitioners",
            name="address",
        ),
        migrations.AddField(
            model_name="practitioner_address",
            name="wheelchair_accessibility",
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name="practitioners",
            name="accessibilities",
            field=models.JSONField(
                default=SafeTagAPI.models.practitioner_model.default_accessibilities
            ),
        ),
        migrations.AddField(
            model_name="practitioners",
            name="addresses",
            field=models.ManyToManyField(to="SafeTagAPI.practitioner_address"),
        ),
        migrations.AddField(
            model_name="practitioners",
            name="api_id",
            field=models.BigIntegerField(default="0", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="practitioner_address",
            name="department",
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_id", models.BigIntegerField()),
                (
                    "addresses",
                    models.ManyToManyField(
                        blank=True, to="SafeTagAPI.practitioner_address"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="practitioners",
            name="organizations",
            field=models.ManyToManyField(blank=True, to="SafeTagAPI.organization"),
        ),
    ]
